name: "Test application"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_container:
          - node:18-alpine
          - node:20-alpine
          - node:22-alpine
          - node:23-alpine
          - node:24-alpine

    env:
      NODE_CONTAINER: ${{ matrix.node_container }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialise environment
        run: make install

      - name: Linting
        run: make lint

      - name: Unit tests
        run: make test

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          verbose: false
